### ISSUE TITLE
Divider name in plugin settings has worng name

### ISSUE THREAD

**Issue by DanilAndreev** [AtlasRender/atlas-monitor#288]
# Describe the bug 👀

Divider in plugin settings has wrong name. Maybe hard coded.

## How to reproduce 🏃:

1. Go to organization page.
2. Click on create plugin.
3. Create plugin with separator.
4. Give a name to the separator.
5. Save plugin.
6. Go to submit job page.
7. Select created plugin.
8. See wrong name onto the separator.

## Expected behavior 🙌
Input name onto the separator.

## Screenshots ✨

![image](https://user-images.githubusercontent.com/33941552/102832130-35e2bd80-43f6-11eb-9c67-e52bbac1f425.png)
![image](https://user-images.githubusercontent.com/33941552/102832148-4135e900-43f6-11eb-812d-5e478b91713d.png)

### Desktop 💻:
 - OS: Windows 10
 - Browser Chrome
 - Version latest

**Comment by ZaykaNya** [comment]
You enter wrong field. Name is unique and not displays. Label is showable name.
